### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by stephenreid321** [autopo-collective/autopo-app#4]
allow feedback on the events
also feedback on individuals?

**Comment by wordsandwriting** [comment]
Wondering if there is an open source feedback tool built into Huddl for peeps to feedback on the La Botica/ Borderlands experience before the memories become faded. Good for us to reflect on ourselves, our achievements, contributions and struggles, the camp, with its different areas, and the festival experience as a whole, highlights, lowlights and everything inbetween.. x
